In [1]:
import cv2
import numpy as np

In [2]:
src = cv2.imread('../1/circles.jpg')#두번째 인자 Default는 Color
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
ret, res = cv2.threshold(gray, 128, 255, cv2.THRESH_BINARY_INV)

cv2.imshow('src', src)
cv2.imshow('res', res)
cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
ret, labels, stats, centroids = cv2.connectedComponentsWithStats(res)#ret은 컴포넌트 개수(하나는 백그라운드), stats는 각 컴포넌트의 바운딩 박스, centroids는 각 컴포넌트의 중점
print('ret=', ret)
print('stats=', stats)
print('centroids=', centroids)

ret= 4
stats= [[     0      0    512    512 222719]
 [   308     86    125    125  12281]
 [   153    145    152    152  18152]
 [   292    338    107    107   8992]]
centroids= [[247.77339607 258.80937863]
 [370.         148.        ]
 [228.5        220.50534376]
 [345.00077847 390.99477313]]


In [4]:
dst = np.zeros(src.shape, dtype=src.dtype)
for i in range(1, int(ret)):
    r = np.random.randint(256)
    g = np.random.randint(256)
    b = np.random.randint(256)
    dst[labels==i] = [b, g, r]#label이 i일때 dst에 색을 넣어라.

In [5]:
for i in range(1, int(ret)):
    x, y, w, h, a = stats[i]
    cv2.rectangle(dst, (x,y), (x+w, y+h), (0,0,255), 2)
    cx, cy = centroids[i]
    cv2.circle(dst, (int(cx), int(cy)), 5, (255,0,0),-1)
    
cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()